###### Server ######
server:
  port: 6060
  servlet:
    context-path: /orders

###### Spring ######
spring:
  application:
    name: order-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # ${DB_URL}
    username: postgres # ${DB_USERNAME}
    password: pass # ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml