###### Server ######
server:
  port: 6060
  servlet:
    context-path: /orders

###### Spring ######
spring:
  application:
    name: order-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # ${DB_URL}
    username: postgres # ${DB_USERNAME}
    password: pass # ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: -1ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      batch-size: 131072      # 128 KB
      buffer-memory: 33554432     # 32MB
      compression-type: lz4
      properties:
        linger.ms: 5
        request.timeout.ms: 30000
        delivery.timeout.ms: 120000
        retry.backoff.ms: 1000
        max.block.ms: 60000
        enable-idempotence: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name:order-service}
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
outbox:
  scheduler:
    enabled: true
    lock:
      environment: prod
      keyPrefix: order-ms
    process-batch-size: 10

kafka:
  order-event-topic: order-event-topic
  payment-event-topic: payment-events-topic
